/*
  # Disable RLS for Full Access
  
  Temporarily disable RLS on all tables to allow full database access.
  This removes authentication barriers for development/testing.
*/

ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_company_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE template_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_customer_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_public_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateway_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE google_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE philippine_holidays DISABLE ROW LEVEL SECURITY;
